# Generated by Django 5.0.4 on 2024-04-19 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mascota',
            new_name='Mascotas',
        ),
    ]
